# Generated by Django 3.0.2 on 2020-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Requested', 'Requested'), ('Cancelled', 'Cancelled'), ('Rejecyed', 'Rejected')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
