# Generated by Django 3.0.2 on 2020-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date_and_time',
            new_name='request_date',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Requested', 'Requested'), ('Cancelled', 'Cancelled'), ('Rejecyed', 'Rejected'), ('Completed', 'Completed')], max_length=10, null=True),
        ),
    ]
