# Generated by Django 3.0.2 on 2020-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20200412_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
