# Generated by Django 3.0.2 on 2020-03-21 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('one', '0002_auto_20200321_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Requested', 'Requested'), ('Cancelled', 'Cancelled'), ('Rejecyed', 'Rejected'), ('Completed', 'Completed')], default='Requested', max_length=10, null=True),
        ),
    ]
